In [31]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics
from sklearn.metrics import classification_report, confusion_matrix
import pickle
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [32]:
data=pd.read_csv('train.csv')
data.head(10)

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000001                      188          1          0   
1  F00000003                      209          1          0   
2  F00000004                      257          1          0   
3  F00000005                      257          1          1   
4  F00000006                      342          1          0   
5  F00000008                      448          0          1   
6  F00000009                      448          0          1   
7  F00000010                      577          1          0   
8  F00000012                      731          0          0   
9  F00000020                     1132          1          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                0.0   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   
5                       1                  0                NaN   
6                       1                  0                NaN   
7                       1                  0                0.0   
8                       1                  0                0.0   
9                       1                  0                0.0   

   Number_Weeks_Quit  Season  Crop_Damage  
0                  0       1            0  
1                  0       2            1  
2                  0       2            1  
3                  0       2            1  
4                  0       2            1  
5                  0       2            1  
6                  0       2            1  
7                  0       1            2  
8                  0       2            0  
9                  0       1            2

In [33]:
print(data.dtypes)

ID                          object
Estimated_Insects_Count      int64
Crop_Type                    int64
Soil_Type                    int64
Pesticide_Use_Category       int64
Number_Doses_Week            int64
Number_Weeks_Used          float64
Number_Weeks_Quit            int64
Season                       int64
Crop_Damage                  int64
dtype: object


In [34]:
print(data.describe())

       Estimated_Insects_Count     Crop_Type     Soil_Type  \
count             88858.000000  88858.000000  88858.000000   
mean               1399.012210      0.284375      0.458417   
std                 849.048781      0.451119      0.498271   
min                 150.000000      0.000000      0.000000   
25%                 731.000000      0.000000      0.000000   
50%                1212.000000      0.000000      0.000000   
75%                1898.000000      1.000000      1.000000   
max                4097.000000      1.000000      1.000000   

       Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
count            88858.000000       88858.000000       79858.000000   
mean                 2.264186          25.849952          28.623970   
std                  0.461772          15.554428          12.391881   
min                  1.000000           0.000000           0.000000   
25%                  2.000000          15.000000          20.000000   
50%            

In [35]:
print(data.shape)

(88858, 10)


In [36]:
print(data.isnull().sum())

ID                            0
Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          9000
Number_Weeks_Quit             0
Season                        0
Crop_Damage                   0
dtype: int64


In [37]:
print(data.isna().sum())

ID                            0
Estimated_Insects_Count       0
Crop_Type                     0
Soil_Type                     0
Pesticide_Use_Category        0
Number_Doses_Week             0
Number_Weeks_Used          9000
Number_Weeks_Quit             0
Season                        0
Crop_Damage                   0
dtype: int64


In [38]:
data['Number_Weeks_Used'].fillna(20, inplace=True)

In [39]:
data.head(10)

ID  Estimated_Insects_Count  Crop_Type  Soil_Type  \
0  F00000001                      188          1          0   
1  F00000003                      209          1          0   
2  F00000004                      257          1          0   
3  F00000005                      257          1          1   
4  F00000006                      342          1          0   
5  F00000008                      448          0          1   
6  F00000009                      448          0          1   
7  F00000010                      577          1          0   
8  F00000012                      731          0          0   
9  F00000020                     1132          1          0   

   Pesticide_Use_Category  Number_Doses_Week  Number_Weeks_Used  \
0                       1                  0                0.0   
1                       1                  0                0.0   
2                       1                  0                0.0   
3                       1                  0                0.0   
4                       1                  0                0.0   
5                       1                  0               20.0   
6                       1                  0               20.0   
7                       1                  0                0.0   
8                       1                  0                0.0   
9                       1                  0                0.0   

   Number_Weeks_Quit  Season  Crop_Damage  
0                  0       1            0  
1                  0       2            1  
2                  0       2            1  
3                  0       2            1  
4                  0       2            1  
5                  0       2            1  
6                  0       2            1  
7                  0       1            2  
8                  0       2            0  
9                  0       1            2

In [40]:
print(data.isnull().sum())

ID                         0
Estimated_Insects_Count    0
Crop_Type                  0
Soil_Type                  0
Pesticide_Use_Category     0
Number_Doses_Week          0
Number_Weeks_Used          0
Number_Weeks_Quit          0
Season                     0
Crop_Damage                0
dtype: int64


In [41]:
data.drop('ID',axis=1,inplace=True)

In [42]:
data.head()

Estimated_Insects_Count  Crop_Type  Soil_Type  Pesticide_Use_Category  \
0                      188          1          0                       1   
1                      209          1          0                       1   
2                      257          1          0                       1   
3                      257          1          1                       1   
4                      342          1          0                       1   

   Number_Doses_Week  Number_Weeks_Used  Number_Weeks_Quit  Season  \
0                  0                0.0                  0       1   
1                  0                0.0                  0       2   
2                  0                0.0                  0       2   
3                  0                0.0                  0       2   
4                  0                0.0                  0       2   

   Crop_Damage  
0            0  
1            1  
2            1  
3            1  
4            1

In [43]:
X, Y = data.drop(["Crop_Damage"], axis=1), data["Crop_Damage"]

In [44]:
print(X.shape,Y.shape)

(88858, 8) (88858,)


In [45]:
def calc_vif(X):

    # Calculating VIF
    vif = pd.DataFrame()
    vif["variables"] = X.columns
    vif["VIF"] = [variance_inflation_factor(X.values, i) for i in range(X.shape[1])]

    return(vif)

In [46]:
calc_vif(X)

variables        VIF
0  Estimated_Insects_Count   6.786242
1                Crop_Type   1.755349
2                Soil_Type   2.047619
3   Pesticide_Use_Category  15.682213
4        Number_Doses_Week   3.949092
5        Number_Weeks_Used  12.376359
6        Number_Weeks_Quit   2.975665
7                   Season   7.346217

In [47]:
X, Y = data.drop(["Crop_Damage","Number_Weeks_Used","Pesticide_Use_Category"], axis=1), data["Crop_Damage"]

In [48]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3, random_state=42,train_size=0.7)

In [49]:
dt=DecisionTreeClassifier()
dt.fit(X_train,y_train)
pred=dt.predict(X_test)
pred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, pred)

0.7842298747092805

In [51]:
report1 = classification_report(y_test,pred)
print(report1)

              precision    recall  f1-score   support

           0       0.85      0.91      0.88     22256
           1       0.25      0.18      0.21      3697
           2       0.09      0.04      0.06       705

    accuracy                           0.78     26658
   macro avg       0.40      0.38      0.38     26658
weighted avg       0.75      0.78      0.77     26658



In [52]:
from sklearn.ensemble import RandomForestClassifier
rf=RandomForestClassifier(n_estimators=50)
rf.fit(X_train,y_train)
prediction=rf.predict(X_test)
prediction

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [53]:
accuracy_score(y_test, prediction)

0.8029109460574687

In [54]:
report2 = classification_report(y_test, prediction)
print(report2)

              precision    recall  f1-score   support

           0       0.86      0.93      0.89     22256
           1       0.30      0.18      0.23      3697
           2       0.11      0.04      0.06       705

    accuracy                           0.80     26658
   macro avg       0.42      0.38      0.39     26658
weighted avg       0.76      0.80      0.78     26658



In [55]:
from lightgbm import LGBMClassifier
model = LGBMClassifier(random_state=27, max_depth=6, n_estimators=400)
model.fit(X_train,y_train)
pr=model.predict(X_test)
accuracy_score(y_test, pr)

0.8386975767124315

In [56]:
report3 = classification_report(y_test, pr)
print(report3)

              precision    recall  f1-score   support

           0       0.85      0.99      0.91     22256
           1       0.51      0.09      0.15      3697
           2       0.25      0.01      0.01       705

    accuracy                           0.84     26658
   macro avg       0.53      0.36      0.36     26658
weighted avg       0.78      0.84      0.78     26658



In [57]:
Pkl_Filename = "agri.pkl"  
pickle.dump(model, open(Pkl_Filename, 'wb'))

In [58]:
with open(Pkl_Filename, 'rb') as file:  
    Pickled_LR_Model = pickle.load(file)

In [59]:
Pickled_LR_Model

LGBMClassifier(max_depth=6, n_estimators=400, random_state=27)

In [60]:
Ypredict = Pickled_LR_Model.predict([[209,1,0,0,0.0,2]])  

Ypredict

array([1], dtype=int64)